### PR TITLE
Use basic authentication for github api to retrieve contributors

### PR DESCRIPTION
**Pull request by Coornail**

### CODE REVIEW

**Comment by pavelloz** [comment]
Does this mean we will have login/pw of someone's GH account in DB in plain text? ;)

**Comment by Coornail** [comment]
You are right, we should use personal access tokens, I will change it accordingly.

**Comment by Coornail** [comment]
Since the documentation repo is open-source, seems like we do not need to use authentication to retrieve the commits:
https://api.github.com/repositories/131636695/commits?path=

**Comment by Coornail** [comment]
Deprecating in favor of: https://github.com/mdyd-dev/nearme-documentation/pull/918

**Pull request closed without merging**
