### PR TITLE
Fixed typos based on Grammarly check.

### PR DESCRIPTION
**Pull request by szabosteve**
Based on Issue #327, I checked some docs by using Grammarly (you can find the list of checked pieces below) and make some changes in three files (**Get started**: *installing-npm-windows.liquid*; **How platform.OS works**: *about-platform-os.liquid*; *technologies.liquid*)

I reviewed the following topics:

**Get started**:
* Accessing the Partner Portal
* Setting Up a Site on Our Platform
* Installing NPM on a Mac
* Installing NPM on Windows
* Installing the Marketplace Kit
* Updating the Marketplace Kit
* Creating the Required Directory Structure
* Deploying and Syncing Changes
* Development Workflow

**How platform.OS works**:
* About platform.OS
* platformOS Components
* Technologies

TBC

### CODE REVIEW

**Review by pavelloz — APPROVED** [review]

**Review by diana-lakatos — APPROVED** [review]
Thank you very much, @szabosteve!

**Comment by szabosteve** [comment]
Sure, no problem @diana-lakatos!

**Comment by pavelloz** [comment]
Thank you :)

**Comment by szabosteve** [comment]
You're welcome! :)

**Pull request merged**
