### PR TITLE
Direct s3 upload

### PR DESCRIPTION
**Pull request by pavelloz**
Explanation of reasoning behind s3 upload.

Preview: https://pawel-docs.staging.oregon.platform-os.com/developer-guide/user-uploads/user-uploads

---

Broader context for https://github.com/mdyd-dev/nearme-documentation/issues/930

Will need to wait for:
* diagrams,
* maybe some more FAQ Q's,
* and hopefully https://github.com/mdyd-dev/desksnearme/issues/9351 fixed before we release (as it is a bummer).

### CODE REVIEW

**Comment by diana-lakatos** [comment]
Thank you! Reviewed and edited.

**Comment by pavelloz** [comment]
Ok, lets wait for images then :)

**Comment by pavelloz** [comment]
Images added, edited so they are editable (and i already had to edit them, so worth spent time), optimized.

Article added to nav

Preview:
https://pawel-docs.staging.oregon.platform-os.com/developer-guide/user-uploads/user-uploads

**Review by diana-lakatos — APPROVED** [review]
Reviewed and edited, thank you!

**Pull request merged**
