### PR TITLE
Create configuring-test-email.liquid

### PR DESCRIPTION
**Pull request by diana-lakatos**
Configuring a Test Email tutorial for the Get Started/Partner Portal section.

### CODE REVIEW

**Comment by diana-lakatos** [comment]
@kv109 I wrote a tutorial for configuring a test email, both because of the client request and because it's needed as a requirement for the email notifications tutorials. 
Please review! Thank you!

**Review by kv109 — APPROVED** [review]

**Comment by pavelloz** [comment]
It would be nice to mention that you can add multiple emails, separated by commas.

"mail1@example.com, mail2@example.com"

It would be also nice to make it an array, but whatever ;)

**Comment by pavelloz** [comment]
@kv109 @diana-lakatos

**Comment by kv109** [comment]
@pavelloz it's there: https://github.com/mdyd-dev/nearme-documentation/pull/75/files#diff-3284a5380f54f4b7902777cc4185f785R39

**Comment by pavelloz** [comment]
👍

**Pull request merged**
