### PR TITLE
Create adding-hcaptcha-spam-protection.liquid

### LINKED ISSUE #1365: Document hcaptcha
Announced in https://documentation.platformos.com/release-notes/22-FEBRUARY-2021

### PR DESCRIPTION
**Pull request by diana-lakatos**
Preview: https://diana-documentation.staging.oregon.platform-os.com/developer-guide/integrations/adding-hcaptcha-spam-protection

Fixes: #1365 

(I will add it to the navigation once it's merged.) 

@andrew-3 Please review and edit/add anything that you think should be improved. Thank you!

### CODE REVIEW

**Comment by andrew-3** [comment]
We should probably also add an example without pOS forms (1) and one for protecting regular pages (2):

1.) For this we would just add a regular form in a page (no form configuration) with the hcaptcha tags inside. This form would post to a page which would have an authorization policy with the same content as in your existing example.

2.) To protect page with slug /main-content, we would create two pages:

/main-content
and
/content-protection

/main-content would have an authorization policy with the same content as above, and would redirect_to /content-protection (when the hcaptcha check fails). /content-protection would have a regular form in it (no form configuration) with hcaptcha tags inside and would post to /main-content (in this way main-content is hcaptcha protected by content-protection).

Please let me know in case you want me to provide detailed working code samples.

Thanks!

**Comment by andrew-3** [comment]
@diana-lakatos ^

**Comment by diana-lakatos** [comment]
@andrew-3 Thank you! Yes, please provide working code examples, we are now striving to add code examples to all of our topics.

**Comment by richxrich** [comment]
A YML / graphql mutation version has been released on staging, you wont need two files shortly just a regular form and a configuration in the header.

**Comment by diana-lakatos** [comment]
@andrew-3 I extended the topic with the 2 examples you provided, please review. Thank you!
You can find the preview on my staging here: https://diana-documentation.staging.oregon.platform-os.com/developer-guide/integrations/adding-hcaptcha-spam-protection

**Comment by andrew-3** [comment]
@diana-lakatos Looks good, for example 1 we should add this authorization_policy as well (referenced in regular_page_post.liquid) - I forgot to add it to the archive I gave you:

```
---
name: check_regular_hcaptcha_authorized
redirect_to: /unauthorized
flash_alert: Sorry
---
{{ params | hcaptcha }}
```

Thanks!

**Comment by diana-lakatos** [comment]
@andrew-3 Thank you! I added the authorization_policy, please check it out and approve if it's good to go live. 
Preview: https://diana-documentation.staging.oregon.platform-os.com/developer-guide/integrations/adding-hcaptcha-spam-protection 

Thank you!

**Review by andrew-3 — APPROVED** [review]

**Pull request merged**
