### PR TITLE
[WIP] update documentation to the newest approach and remove deprecated concepts

### PR DESCRIPTION
**Pull request by Slashek**
Please note - this can 💥 something as I have not done much testing - rely on automated tests :)

Deployed to https://documentation-qa.staging.oregon.platform-os.com/ for manual tests

- [ x ] - do not use `_` in partial names
- [ x ] - remove Relationship, RelationshipUser, RelationshipTransactable, Order, BankAccount, CreditCard 
- [ x ] - do not use `params`, use `context.params`
- [ x ] - do not use resource: Customization in our forms, use concrete name without passing parent_resource_id or resource_type to include form
- [ x ] - use `fields` instead of `configuration` 
- [ x ] - use `properties` instead of custom attributes
- [ x ] - do not rely on public scope for include for navLinks - use `export` tag

### CODE REVIEW

**Comment by pavelloz** [comment]
@jnorbert can you test forms/notifications? :)

**Comment by jnorbert** [comment]
@Slashek after clicked on search occurred error.
http://take.ms/u6noU

**Comment by jnorbert** [comment]
@Slashek lack of content in email sending from the page 
https://documentation-qa.staging.oregon.platform-os.com/contact
http://take.ms/pSxP4

**Comment by pavelloz** [comment]
Looks good to close ;)

**Comment by pavelloz** [comment]
Because this is going nowhere i started doing it on my own.
Ill create issue for myself to fix things that are still there to do left.

**Pull request closed without merging**
