### PR TITLE
add documentation for config

### PR DESCRIPTION
**Pull request by Slashek**

### CODE REVIEW

**Comment by diana-lakatos** [comment]
Reviewed and edited, thank you!

**Comment by pavelloz** [comment]
I propose not doing it in a table, but just header 3 + paragraphs. There is enough content for table to be barely readable ;)

**Comment by Slashek** [comment]
hm yeah, worth considering @pavelloz  , there are pros and cons - with the table it's easy to skim through all the options IMO. Let's merge it for now, but I don't mind re-structuring it if you find it a better fit.

**Comment by pavelloz** [comment]
Yup, i think it should be its own article, so it shows in search as a first class citizen

**Pull request merged**
