### PR TITLE
Update directory structure tree

### PR DESCRIPTION
**Pull request by pavelloz**

### CODE REVIEW

**Review by diana-lakatos — COMMENTED** [review]
@pavelloz 
In the Codebase topic, we present each directory one by one, so this doesn't fit the structure of the article. What we could do is leave the assets directory with the examples here, and have an overview of all directories and files in the beginning of the article. What do you think?

**Comment by pavelloz** [comment]
Ouh right, i edited the wrong place

This is what i ment to change: https://documentation.platformos.com/get-started/hello-world/create-codebase

Ill fix that

**Comment by pavelloz** [comment]
Additionally, tomorrow it will change again, because of notifications updates

**Comment by diana-lakatos** [comment]
Thank you!

**Pull request merged**
