### PR TITLE
update documentation about context

### PR DESCRIPTION
**Pull request by Slashek**

### CODE REVIEW

**Review by pavelloz — APPROVED** [review]

**Comment by pavelloz** [comment]
cc @diana-lakatos i merged too early, if you have any edits go ahead ;)

**Comment by Slashek** [comment]
would be good to wait for the PR to be merged 🙈 should have marked it somehow :)

**Comment by pavelloz** [comment]
Its okay, it wont get to prod until we do it manually :)

**Comment by diana-lakatos** [comment]
> cc @diana-lakatos i merged too early, if you have any edits go ahead ;)

Reviewed and added some minor edits. Thank you!

**Pull request merged**
