### PR TITLE
Add try now button, fix last edit

### LINKED ISSUE #990: Add a menu link to the journey selector page
Make the journey selector page available by adding a menu link to it:
https://documentation.platformos.com/try-now

[Wireframe](https://www.figma.com/file/FEluBi25T6PrfuBjazt0hn/Wireframes?node-id=204%3A230)

### PR DESCRIPTION
**Pull request by pavelloz**
Fixes https://github.com/mdyd-dev/nearme-documentation/issues/990

Preview: https://pawel-docs.staging.oregon.platform-os.com/try-now

### CODE REVIEW

**Comment by pavelloz** [comment]
Also fixes https://github.com/mdyd-dev/nearme-documentation/issues/975

Preview: https://pawel-docs.staging.oregon.platform-os.com/release-notes

**Review by diana-lakatos — APPROVED** [review]
Looks good to me, @Nagygyorgy please confirm if the Try Now page is ready to go live. 
Thank you!

**Comment by Nagygyorgy** [comment]
@pavelloz @diana-lakatos Looks great! I'd only like to ask a small change related to the text color of the button statuses. Sorry, it wasn't defined on the wireframes.
- Normal state - text is white
- Hover and Selected state  - text is grey
Could you change it accordingly? 
Thanks

**Comment by pavelloz** [comment]
Reversed, preview: https://pawel-docs.staging.oregon.platform-os.com/

**Pull request merged**
