### PR TITLE
Data update

### PR DESCRIPTION
**Pull request by piotrze**

### CODE REVIEW

**Comment by pavelloz** [comment]
LGTM, but i think we use `*` as list in our markdown files so far ;)

**Review by pavelloz — APPROVED** [review]

**Comment by diana-lakatos** [comment]
> LGTM, but i think we use `*` as list in our markdown files so far ;)

Both are valid Markdown, so let's grant authors that much artistic freedom. :)

**Review by diana-lakatos — APPROVED** [review]
Reviewed and edited. Thank you!

**Comment by diana-lakatos** [comment]
Closes #461

**Pull request merged**
