### PR TITLE
Reset Password Flow fixes

### PR DESCRIPTION
**Pull request by JoshCarterWeb**

### CODE REVIEW

**Comment by JoshCarterWeb** [comment]
@pavelloz I'm happy with these changes if you could check over?

**Comment by pavelloz** [comment]
LGTM

I would personally cache `g.results.users[0]` to not have to write it every time, but code itself should work.

**Comment by JoshCarterWeb** [comment]
Out of curiosity, is there any performance negative to reassigning `g.results.users[0]` to `user`? Or is it negligible and so it's best to reassign for readability?

**Comment by pavelloz** [comment]
Only readability and ease of use in maintenance :)

**Comment by Developer-DNM** [comment]
Thanks for your contribution to this @JoshCarterWeb 👍

**Pull request merged**
