### PR TITLE
Expand article on using GraphiQL

### PR DESCRIPTION
**Pull request by pavelloz**
Preview: https://pawel-docs.staging.oregon.platform-os.com/best-practices/qa/developing-graphql-queries-using-pos-cli-gui

### CODE REVIEW

**Comment by pavelloz** [comment]
Fixes #942

**Review by diana-lakatos — APPROVED** [review]
Reviewed and edited. Thank you!

**Comment by pavelloz** [comment]
BTW. When i was writing this, i realized that there is almost none information on how to use graphiql in text/video anywhere. 

This means that we could change title from `Developing GraphQL Queries Using pos-cli gui` to `Developing GraphQL Queries Using GraphiQL` - which even technically is even more correct, because gui just starts GraphiQL and we could improve SEO and bring some beginners from graphql world


@diana-lakatos

**Comment by diana-lakatos** [comment]
@pavelloz Thanks! I will do the renaming together with moving the topic to the Developer Guide.

**Pull request merged**
