### PR TITLE
Section on module templates

### PR DESCRIPTION
**Pull request by ignacy**
https://github.com/mdyd-dev/nearme-documentation/issues/468

### CODE REVIEW

**Review by diana-lakatos — APPROVED** [review]
Reviewed and edited. 
This can be used as the concept topic for module templates, that describes the background information,  provides an example, and includes a section (Related topics) that links to tutorials, tutorial series and other concept topics if needed. 

For users to be able to use module templates, we'd need at least one more separate topic, a step by step tutorial that walks the user through creating a module template, shows how to try it out and shows the result.

**Comment by diana-lakatos** [comment]
Please don't merge until the feature has been tested and a tutorial has been added. Thanks!

**Comment by diana-lakatos** [comment]
@ignacy Please verify the folder structure example I added. Thank you!

**Comment by ignacy** [comment]
@diana-lakatos confirmed, the sctructure is correct: `template-values.json` is on the same level as private and public folders

**Review by diana-lakatos — APPROVED** [review]
Reviewed and edited. 
I'm working on a separate tutorial for configuring module templates on the Partner Portal.

**Comment by diana-lakatos** [comment]
Available on the Partner Portal, ready to merge.

**Pull request merged**
