### PR TITLE
Added info about where to store API endpoints

### PR DESCRIPTION
**Pull request by z-x**
Added this information as I was wondering myself, but there is no 'Learn more' link currently it seems. It might be a good idea to write a simple article about how to prepare a basic endpoint in the future.

### CODE REVIEW

**Comment by diana-lakatos** [comment]
Thank you!

**Comment by pavelloz** [comment]
Hmm, article is about where files have to be to do something, and this `pages/api` directory is basically a convention, you can use `views/pages` to do that. Its not required, its just someone's preference.

Having separate article would be probably a better way of handling it, with example of `pages/api` as our preference.
It should be a really short article:
* Pick a slug
* use a json format
* request it in the client using url with .json

**Comment by z-x** [comment]
@Slashek and @godot I am summoning you two here as we had a talk about this and your opinions might be nice here. :)

**Comment by Slashek** [comment]
@z-x I share Pawel's thoughts. This article shows a built-in directory structure, which is mandatory. On the other hand, `views/pages/api` is something that can vary based on the project. You can put your API pages in any directory you want, like `views/pages/rest`, `views/pages/v1/` etc. This is from the perspective of platformOS being a platform. I would see this addition in the Marketplace Template repository, which is a concrete project hosted on platformOS, and within that project we made the decision described here. But because we do not force such convention, in my opinion, it does not belong here.

**Comment by z-x** [comment]
Since I understood that this is a global thing and I should add this to documentation from our talk and it seems it's not then I can close this PR. :)

**Pull request closed without merging**
