### PR TITLE
Add configuration options article

### LINKED ISSUE #438: Describe all Partner Portal flags that change instance behavior
Information should include:

* description
* default value
* possible values

Flags:

* test_mode
* test_email
* maintenance_mode
* include_tag_with_private_scope
* skip_action_types_and_pricings
* enable_sms_and_api_workflow_alerts_on_staging

### PR DESCRIPTION
**Pull request by pavelloz**
I didnt know where to put this article, so its not added to navigation, filename/slug/description is also half baked.

@diana-lakatos :)

Fixes #438

### CODE REVIEW

**Comment by diana-lakatos** [comment]
Adding all the information about the options here based on discussion with Pawel: https://documentation.platform-os.com/tutorials/partner-portal/updating-instance-configuration

**Comment by pavelloz** [comment]
Waiting for your intervention then :)

**Comment by lemingos** [comment]
I've just added https://github.com/mdyd-dev/desksnearme/pull/8002 maybe we could add that as well

**Comment by pavelloz** [comment]
After QA, merge, etc.

**Pull request closed without merging**
