### PR TITLE
Section on `context.modules`

### PR DESCRIPTION
**Pull request by ignacy**
Add section on `context.modules` tag

### CODE REVIEW

**Comment by diana-lakatos** [comment]
@ignacy Thank you! Do you think this should be a separate topic? Are you planning to extend it? 
As it is currently, I think it could be a section in the Modules concept topic: https://documentation.platform-os.com/tutorials/modules/modules 
What do you think?

**Comment by pavelloz** [comment]
or https://documentation.platform-os.com/tutorials/variables/context-variable

**Comment by ignacy** [comment]
👍 Moved to https://documentation.platform-os.com/tutorials/variables/context-variable

**Review by diana-lakatos — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
